version: "3.8"

services:
  support_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: support-bot
    restart: unless-stopped
    env_file:
      - .env
    command: ["support_bot"]
    volumes:
      - ./logs/bot:/app/logs

  weather_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-bot
    restart: unless-stopped
    env_file:
      - .env
    command: ["weather_bot"]
    volumes:
      - ./logs/bot:/app/logs

  welcome_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: welcome-bot
    restart: unless-stopped
    env_file:
      - .env
    command: ["welcome_bot"]
    volumes:
      - ./logs/bot:/app/logs