version: "3.8"

services:
  support_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: support-bot
    restart: unless-stopped
    env_file:
      - .env
    command: ["--config=configs/support_bot.yaml"]
    volumes:
      - ./logs/bot:/app/logs

  weather_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-bot
    restart: unless-stopped
    env_file:
      - .env
    command: ["--config=configs/weather_bot.yaml"]
    volumes:
      - ./logs/bot:/app/logs

  welcome_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: welcome-bot
    restart: unless-stopped
    env_file:
      - .env
    command: ["--config=configs/welcome_bot.yaml"]
    volumes:
      - ./logs/bot:/app/logs

  hype:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hype
    restart: unless-stopped
    env_file:
      - .env
    command: ["--config=configs/hype.yaml"]
    volumes:
      - ./logs/bot:/app/logs